### ISSUE TITLE
Error being spammed

### ISSUE THREAD

**Issue by Wilsoon7721** [Xericore/EasyCarts#10]
I am running EasyCarts for 1.8 and I keep getting this error. Any idea how to fix?

Plugins:
![image](https://user-images.githubusercontent.com/40225169/69242587-21713780-0bdc-11ea-8fe5-beaa3e44118d.png)

[PaperSpigot Error](https://pastebin.com/ZKgcigix)

The error is flooding my Console whenever I'm riding a minecart on a track.

I am running PaperSpigot 1.8.8.

[Config](https://pastebin.com/52AsrJfs)

EDIT:
I changed to Normal Spigot 1.8.8 and received a different error instead.

[Spigot Error](https://pastebin.com/Efxrxak3)

Whats wrong?
None of the settings are being applied while the errors are broadcasted.

**Comment by Wilsoon7721** [comment]
Found out the issue, seems like its because PaperSpigot has excessive velocity checks, as long as the plugin doesnt crash the server, then the checks can be turned off in paper.yml, you are fine.
As for Spigot....

**Comment by Xericore** [comment]
Thanks for the info.
