### ISSUE TITLE
1.15 Left Click In Vehicle Issue

### ISSUE THREAD

**Issue by GrantFBG** [Xericore/EasyCarts#12]
After Using This Plugin In My 1.15 Survival Server (On Paper 353), I Noticed Some Issues. Whilst Riding Within Other Vehicles, You Can Get A Speed Boost By Left Clicking (Similar To The Minecarts).

**Comment by Xericore** [comment]
I've just released EasyCarts 2.1 that fixes this issue.
https://www.spigotmc.org/resources/easycarts.3941/
