### ISSUE TITLE
Craftbook stations not always working

### ISSUE THREAD

**Issue by Bloodlex** [Xericore/EasyCarts#15]
Hey,

I'm not sure if that is related with EasyCarts, but I have an issue that my Craftbook minecraft stations don't work properly for most of the time (that means it doesn't stop minecart every time as it should 🙁 ).

I'm sure I set up my stations properly laying down obsidian and sign with [station] in the 2 line below.

Thank you for this awesome plugin and you support! 🙂

**Comment by Xericore** [comment]
Hi Bloodlex,
EasyCarts only affects minecarts with players in it. All other carts are ignored. It shouldn't interfere with CraftBook stations. The only thing it can interfere with is CraftBook intersections. Do you experience the issue also without EasyCarts?
Thanks and best regards.

**Comment by Bloodlex** [comment]
Hey @Xericore 

Thank you very much for your reply! Yeah, I'm talking here about minecraft with players :) Maybe the speed of a minecart is so high, that a station doesn't have time to react and stop it?

I don't use craftbook intersections, only a simple rail. I'll try if I have this issue without EasyCarts when my server is empty :). I hope it can be fixed, because transportation is very important for my server :)

This is my EasyCarts config: [https://pastebin.com/XDq2PESK](https://pastebin.com/XDq2PESK)

Enabled mechanics from Craftbook:
enabled-mechanics:
- Variables
- MinecartEjector
- MinecartTemporaryCart
- MinecartStation
- MinecartBooster
- MinecartNoCollide
- MinecartMaxSpeed
- MinecartSpeedModifiers
- BoatSpeedModifiers
- LandBoats
- Gate
- PaintingSwitcher

Best regards,
Bloodlex

**Comment by Xericore** [comment]
Hi,
yes it can happen that a cart that's travelling at a high velocity doesn't fire enough events and thus a single block can't "catch" it. Unfortunately there's little I can do about this.

**Comment by Bloodlex** [comment]
> Hi,
> yes it can happen that a cart that's travelling at a high velocity doesn't fire enough events and thus a single block can't "catch" it. Unfortunately there's little I can do about this.

Yes I think you're right and it's speed-related think. Okay, I'll see what I can do if there is nothing you can on your side, thank you very much for your help! 🙂 👍
