### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [Xericore/EasyCarts#4]
logs
https://gist.github.com/mat41997/afa2e93cfee665ed2c61529ae121d955

timings
https://timings.aikar.co/?id=b88b26fa399541b8b56a3799d619426d#plugins

**Comment by Xericore** [comment]
Thank you for pointing that out so quickly. EasyCarts 1.8.1 fixes this issue. https://www.spigotmc.org/resources/easycarts.3941/
